#!/bin/bash
mkdir -p public/destinations
curl -s -L -A "Mozilla/5.0" -o "public/destinations/delhi.jpg" "https://upload.wikimedia.org/wikipedia/commons/4/40/Jama_Masjid_2011.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/spiti.jpg" "https://upload.wikimedia.org/wikipedia/commons/e/ec/Spiti_Valley_panorama.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/kasol.jpg" "https://upload.wikimedia.org/wikipedia/commons/a/a2/Kasol_mountain_view.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/manali.jpg" "https://upload.wikimedia.org/wikipedia/commons/0/07/A_view_of_Manali_Town.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/dharamshala.jpg" "https://upload.wikimedia.org/wikipedia/commons/a/a6/Dharamshala_03_%28Cropped%29.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/shimla.jpg" "https://upload.wikimedia.org/wikipedia/commons/b/ba/Landscape_of_Shimla_%2C_Himachal_Pradesh.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/kedarnath.jpg" "https://upload.wikimedia.org/wikipedia/commons/1/1a/Kedarnath_View1.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/badrinath.jpg" "https://upload.wikimedia.org/wikipedia/commons/6/68/Badrinath_Temple-_Uttarakhand.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/auli.jpg" "https://upload.wikimedia.org/wikipedia/commons/9/9d/Auli_hill_station.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/mussoorie.jpg" "https://upload.wikimedia.org/wikipedia/commons/e/e0/Mussoorie_Snow_Over_Dehradun_%2814831297545%29.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/nainital.jpg" "https://upload.wikimedia.org/wikipedia/commons/6/6f/Nainital_metro.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/rishikesh.jpg" "https://upload.wikimedia.org/wikipedia/commons/7/74/Trayambakeshwar_Temple_VK.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/haridwar.jpg" "https://upload.wikimedia.org/wikipedia/commons/0/00/Ganga_aarti_haridwar_01.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/corbett.jpg" "https://upload.wikimedia.org/wikipedia/commons/7/78/Bengal-Tiger_Corbett_Uttarakhand_Dec-2013.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/agra.jpg" "https://upload.wikimedia.org/wikipedia/commons/6/68/Taj_Mahal%2C_Agra%2C_India.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/mathura.jpg" "https://upload.wikimedia.org/wikipedia/commons/c/cc/Vishram_Ghat.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/vrindavan.jpg" "https://upload.wikimedia.org/wikipedia/commons/b/bf/Iskon_Temple%2C_Vrindawan.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/morni.jpg" "https://upload.wikimedia.org/wikipedia/commons/4/45/Morni_Hills_lake.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/kurukshetra.jpg" "https://upload.wikimedia.org/wikipedia/commons/1/13/Kurukshetra_junction_kkde.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/gurugram.jpg" "https://upload.wikimedia.org/wikipedia/commons/d/d6/Cyber_City_View.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/amritsar.jpg" "https://upload.wikimedia.org/wikipedia/commons/e/ea/Golden_Temple_Amritsar_Gurudwara_%28cropped%29.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/ranthambore.jpg" "https://upload.wikimedia.org/wikipedia/commons/7/7f/Ranthambore_National_Park.JPG"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/jaipur.jpg" "https://upload.wikimedia.org/wikipedia/commons/4/41/East_facade_Hawa_Mahal_Jaipur_from_ground_level_%28July_2022%29_-_img_01.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/udaipur.jpg" "https://upload.wikimedia.org/wikipedia/commons/6/6f/Evening_view%2C_City_Palace%2C_Udaipur.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/jaisalmer.jpg" "https://upload.wikimedia.org/wikipedia/commons/4/46/Jaisalmer_Fort.jpg"
curl -s -L -A "Mozilla/5.0" -o "public/destinations/mount-abu.jpg" "https://upload.wikimedia.org/wikipedia/commons/6/6b/Mount_Abu.jpg"
